services:
  mongo:
    image: mongo:7
    container_name: panaderia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: panaderia_app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_MONGODB_URI: mongodb://mongo:27017/panaderia_db
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongo_data: