server:
  port: 8080

spring:
  mongodb:
    uri: mongodb://localhost:27017/panaderia_db

app:
  files:
    asesor:
      upload-dir: uploads/asesores
  sync:
    asesor-url: http://localhost:8082/api/asesores